### ISSUE TITLE
Address compiler warnings

### ISSUE THREAD

**Issue by r-barnes** [zhouguiyun-uestc/ParallelFlowDirections#20]
PR #19 enables the `-Wall -pedantic` flags. Please fix the warnings raised by the compiler so that the code compiles without warnings.

Some of these are merely the wrong variable data type, e.g.
```
../src/flowdir/host.h:52:28: warning: format ‘%s’ expects argument of type ‘char*’, but argument 3 has type ‘int’ [-Wformat=]
```
Others are unused variables which add to code clutter:
```
../include/paradem/tool.h:135:14: warning: ‘g1’ defined but not used [-Wunused-variable]
```
And some refer to places where the code is difficult to understand:
```
../src/flowdir/consumer.cpp:1270:108: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
```
Using inappropriate variables for for-loops is a common issue that can have consequences when larger datasets are used, e.g.:
```
../src/common/tool.cpp:69:36: warning: comparison of integer expressions of different signedness: ‘int’ and ‘long unsigned int’ [-Wsign-compare]
   for ( int tileRow = 0; tileRow < max_row_size; tileRow++ ) {
```
which is fixed with (probably):
```
   for ( size_t tileRow = 0; tileRow < max_row_size; tileRow++ ) {
```
If you'd like any double checks on changes, feel free to flag me to review a PR.

**Comment by zhouguiyun-uestc** [comment]
Done!

**Comment by r-barnes** [comment]
I'm still seeing a couple of warnings:
```
[13/20] Building CXX object CMakeFiles/ParallelFlowDir.dir/src/common/gdal.cpp.o
../src/common/gdal.cpp: In function ‘bool WriteGeoTIFF(const char*, int, int, void*, GDALDataType, double*, double*, double*, double*, double*, double)’:
../src/common/gdal.cpp:24:21: warning: ignoring return value of ‘CPLErr GDALRasterBand::RasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, GSpacing, GSpacing, GDALRasterIOExtraArg*)’, declared with attribute warn_unused_result [-Wunused-result]
   24 |     poBand->RasterIO( GF_Write, 0, 0, width, height, pData, width, height, type, 0, 0 );
      |     ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/common/gdal.cpp: In function ‘bool readGeoTIFF(const char*, GDALDataType, Raster<float>&)’:
../src/common/gdal.cpp:48:21: warning: ignoring return value of ‘CPLErr GDALRasterBand::RasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, GSpacing, GSpacing, GDALRasterIOExtraArg*)’, declared with attribute warn_unused_result [-Wunused-result]
   48 |     poBand->RasterIO( GF_Read, 0, 0, dem.getWidth(), dem.getHeight(), ( void* )&dem, dem.getWidth(), dem.getHeight(), type, 0, 0 );
      |     ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/common/gdal.cpp: In function ‘bool readflowTIFF(const char*, GDALDataType, Raster<int>&)’:
../src/common/gdal.cpp:73:21: warning: ignoring return value of ‘CPLErr GDALRasterBand::RasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, GSpacing, GSpacing, GDALRasterIOExtraArg*)’, declared with attribute warn_unused_result [-Wunused-result]
   73 |     poBand->RasterIO( GF_Read, 0, 0, flow.getWidth(), flow.getHeight(), ( void* )&flow, flow.getWidth(), flow.getHeight(), type, 0, 0 );
      |     ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[17/20] Building CXX object CMakeFiles/ParallelFlowDir.dir/src/common/tool.cpp.o
../src/common/tool.cpp: In function ‘bool generateTiles(const char*, int, int, const char*)’:
../src/common/tool.cpp:168:27: warning: ignoring return value of ‘CPLErr GDALRasterBand::RasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, GSpacing, GSpacing, GDALRasterIOExtraArg*)’, declared with attribute warn_unused_result [-Wunused-result]
  168 |             band->RasterIO( GF_Read, tileWidth * tileCol, tileHeight * tileRow, tile.getWidth(), tile.getHeight(), ( void* )&tile, tile.getWidth(), tile.getHeight(), type, 0, 0 );
      |             ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[20/20] Linking CXX executable ../ParallelFlowDir
```
You should save the return values of your `RasterIO` calls, check to see if they are success codes, and throw an exception (or take some other action) if they fail. See [this](https://github.com/r-barnes/richdem/blob/663220bd1395918e6cb721f093e1b81cd702c722/include/richdem/common/Array2D.hpp#L445-L447) for an example.

**Comment by zhouguiyun-uestc** [comment]
Thanks. Done!

**Comment by r-barnes** [comment]
It looks good on my end too, thanks.
